language: node_js
node_js:
  - "14.0"
services:
  - docker
env:
  - WORK_DIR=15-lesson
script: cd $WORK_DIR

deploy:
  provider: script
  script: bash ./scripts/deploy_heroku.sh
  on:
    branch: 15_lesson
